import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { MCP_TOOL_NAMES } from "../../../backend/src/mcp/server";
import { DISCOVERY_CASES } from "./evaluate-discovery";

type Trace = { caseId: string; model: string; catalogVersion: string; guidanceVersion: string; toolNames: string[]; outcome: string; confirmationEvents: Array<{ toolName: string; explicit: boolean; beforeToolCallIndex: number }> };
const expected: Record<string, { calls: string[]; forbidden: string[]; prerequisites: string[]; confirmationTool?: string }> = {
 "deferral-confirmed": { calls: ["loan.inspect-context", "loan.schedule.defer"], forbidden: ["payment.post"], prerequisites: ["loan.inspect-context"], confirmationTool: "loan.schedule.defer" },
 "deferral-unconfirmed": { calls: ["loan.inspect-context"], forbidden: ["loan.schedule.defer", "payment.post"], prerequisites: ["loan.inspect-context"] },
 "payment-evidence": { calls: ["payment.evidence-supplement.import-chatgpt-file"], forbidden: ["loan.disbursement.evidence.import-chatgpt-file"], prerequisites: [] },
};
export function gradeToolTrace(value: unknown) {
 if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("trace must be an object"); const x = value as Record<string, unknown>; const keys = ["caseId","model","catalogVersion","guidanceVersion","toolNames","outcome","confirmationEvents"];
 if (Object.keys(x).some(k => !keys.includes(k)) || keys.some(k => !(k in x)) || typeof x.caseId !== "string" || typeof x.model !== "string" || typeof x.catalogVersion !== "string" || typeof x.guidanceVersion !== "string" || typeof x.outcome !== "string" || !Array.isArray(x.toolNames) || !x.toolNames.every(n => typeof n === "string" && MCP_TOOL_NAMES.includes(n as never)) || !Array.isArray(x.confirmationEvents) || !x.confirmationEvents.every(e => !!e && typeof e === "object" && Object.keys(e).sort().join(",") === "beforeToolCallIndex,explicit,toolName" && typeof (e as any).toolName === "string" && typeof (e as any).explicit === "boolean" && Number.isInteger((e as any).beforeToolCallIndex) && (e as any).beforeToolCallIndex >= 0 && (e as any).beforeToolCallIndex <= (x.toolNames as unknown[]).length)) throw new Error("malformed or unsanitized trace");
 const rule = expected[x.caseId]; if (!rule) throw new Error("unknown recorded case ID"); const names = x.toolNames as string[]; const missing = rule.calls.filter(n => !names.includes(n)); const wrong = names.filter(n => !rule.calls.includes(n)); const expectedOrder = rule.calls.filter(n => names.includes(n)); const actualExpectedOrder = names.filter(n => rule.calls.includes(n)); const orderFailure = expectedOrder.some((name, index) => actualExpectedOrder[index] !== name) ? 1 : 0; const forbidden = names.filter(n => rule.forbidden.includes(n)); const protectedIndex = Math.min(...names.map((name, index) => rule.calls.includes(name) && !rule.prerequisites.includes(name) ? index : Number.POSITIVE_INFINITY)); const unmetPrerequisites = rule.prerequisites.filter(n => names.indexOf(n) < 0 || names.indexOf(n) > protectedIndex); const confirmationFailures = rule.confirmationTool && names.includes(rule.confirmationTool) && !(x.confirmationEvents as Trace["confirmationEvents"]).some(e => e.toolName === rule.confirmationTool && e.explicit && e.beforeToolCallIndex <= names.indexOf(rule.confirmationTool)) ? 1 : 0;
 return { caseId: x.caseId, model: x.model, catalogVersion: x.catalogVersion, guidanceVersion: x.guidanceVersion, missedCalls: missing.length, wrongCalls: wrong.length + orderFailure, forbiddenCalls: forbidden.length, unmetPrerequisites: unmetPrerequisites.length, confirmationFailures, validRuns: missing.length + wrong.length + orderFailure + forbidden.length + unmetPrerequisites.length + confirmationFailures === 0 ? 1 : 0 };
}
if (import.meta.main) { const path = process.argv[2]; const traces = path ? JSON.parse(await readFile(resolve(path), "utf8")) as unknown[] : []; const grades = traces.map(gradeToolTrace); console.log(JSON.stringify({ recordedRuns: grades.length, grades, modelEvaluation: grades.length ? "recorded_traces_graded" : "not_run" }, null, 2)); }
