import { Elysia, t } from "elysia";
import { invalidateTenantCache } from "../lib/cache";
import { authPlugin } from "../middleware/auth";
import { assertDisbursementParentLoan, createDisbursementDraft, finalizeDisbursementEvidence, listLoanDisbursements, postDisbursement, prepareDisbursementEvidence, rejectDisbursementDraftEvidenceIds, reverseDisbursement, updateDisbursementDraft } from "../services/loan-disbursement-service";
import { loanCommandContext, loanDomainFailure, loanUnauthorized } from "./loan-http-support";

const draft = t.Object({ grossAmount: t.String({ pattern: "^(0|[1-9]\\d*)\\.\\d{2}$", maxLength: 32 }), loanAttributedAmount: t.String({ pattern: "^(0|[1-9]\\d*)\\.\\d{2}$", maxLength: 32 }), channel: t.Union([t.Literal("bank_transfer"), t.Literal("cash"), t.Literal("adjustment")]), sourceBankProfilePublicId: t.Optional(t.Nullable(t.String({ format: "uuid" }))), payeeHint: t.Optional(t.Nullable(t.String({ maxLength: 500 }))), note: t.Optional(t.Nullable(t.String({ maxLength: 2000 }))), disbursedAt: t.String({ format: "date-time" }), evidenceFilePublicIds: t.Optional(t.Array(t.String({ format: "uuid" }), { maxItems: 100 })) });
const ids = t.Object({ id: t.String({ format: "uuid" }), disbursementId: t.String({ format: "uuid" }) });

export const loanDisbursementRoutes = new Elysia().use(authPlugin)
 .get("/:id/disbursements", async ({ params, user, request, set }) => { if (!user) return loanUnauthorized(set); try { return await listLoanDisbursements(loanCommandContext(user, request), params.id); } catch (error) { return loanDomainFailure(error, set); } }, { params: t.Object({ id: t.String({ format: "uuid" }) }) })
 .post("/:id/disbursements", async ({ params, body, user, request, set }) => { if (!user) return loanUnauthorized(set); try { rejectDisbursementDraftEvidenceIds(body); const result = await createDisbursementDraft(loanCommandContext(user, request), params.id, body); await invalidateTenantCache(user.tenantId); return result; } catch (error) { return loanDomainFailure(error, set); } }, { params: t.Object({ id: t.String({ format: "uuid" }) }), body: draft })
 .put("/:id/disbursements/:disbursementId", async ({ params, body, user, request, set }) => { if (!user) return loanUnauthorized(set); try { rejectDisbursementDraftEvidenceIds(body); const ctx = loanCommandContext(user, request); await assertDisbursementParentLoan(ctx, params.id, params.disbursementId); const result = await updateDisbursementDraft(ctx, params.disbursementId, body); await invalidateTenantCache(user.tenantId); return result; } catch (error) { return loanDomainFailure(error, set); } }, { params: ids, body: t.Partial(draft) })
 .post("/:id/disbursements/:disbursementId/evidence/upload-intents", async ({ params, body, user, request, set }) => { if (!user) return loanUnauthorized(set); try { const ctx = loanCommandContext(user, request); await assertDisbursementParentLoan(ctx, params.id, params.disbursementId); return await prepareDisbursementEvidence(ctx, params.disbursementId, body); } catch (error) { return loanDomainFailure(error, set); } }, { params: ids, body: t.Object({ mimeType: t.Union([t.Literal("image/jpeg"), t.Literal("image/png"), t.Literal("application/pdf")]), size: t.Integer({ minimum: 1 }), sha256: t.String({ pattern: "^[0-9a-fA-F]{64}$" }), originalName: t.Optional(t.Nullable(t.String({ maxLength: 500 }))) }) })
 .post("/:id/disbursements/:disbursementId/evidence/:evidenceId/finalize", async ({ params, user, request, set }) => { if (!user) return loanUnauthorized(set); try { const ctx = loanCommandContext(user, request); await assertDisbursementParentLoan(ctx, params.id, params.disbursementId); return await finalizeDisbursementEvidence(ctx, params.disbursementId, params.evidenceId); } catch (error) { return loanDomainFailure(error, set); } }, { params: t.Object({ ...ids.properties, evidenceId: t.String({ format: "uuid" }) }) })
 .post("/:id/disbursements/:disbursementId/post", async ({ params, user, request, set }) => { if (!user) return loanUnauthorized(set); try { const ctx = loanCommandContext(user, request); await assertDisbursementParentLoan(ctx, params.id, params.disbursementId); const result = await postDisbursement(ctx, params.disbursementId); await invalidateTenantCache(user.tenantId); return result; } catch (error) { return loanDomainFailure(error, set); } }, { params: ids, body: t.Object({}) })
 .post("/:id/disbursements/:disbursementId/reverse", async ({ params, body, user, request, set }) => { if (!user) return loanUnauthorized(set); try { const ctx = loanCommandContext(user, request); await assertDisbursementParentLoan(ctx, params.id, params.disbursementId); const result = await reverseDisbursement(ctx, params.disbursementId, body.reason); await invalidateTenantCache(user.tenantId); return result; } catch (error) { return loanDomainFailure(error, set); } }, { params: ids, body: t.Object({ reason: t.String({ minLength: 1, maxLength: 2000 }) }) });
