import { Elysia, t } from "elysia";
import { authPlugin } from "../middleware/auth";
import type { CommandContext } from "../services/command-context";
import { DomainError, presentDomainError } from "../services/domain-error";
import { discoverPaymentBatchCandidates } from "../services/payment-batch-candidate-service";
import { addPaymentBatchItem, cancelPaymentBatch, createPaymentBatch, decidePaymentBatch, editPaymentBatchStagingItem, executePaymentBatch, finalizePaymentBatchStagingEvidence, getPaymentBatch, getPaymentBatchWorkspace, preparePaymentBatchStagingEvidence, previewPaymentBatch, reviewPaymentBatchStagingItem, splitPaymentBatch, stagePaymentBatchItems } from "../services/payment-batch-service";

type RouteUser = { id: number; tenantId: string };
function ctx(user: RouteUser, request: Request): CommandContext { const requestId = request.headers.get("x-request-id") ?? crypto.randomUUID(); return { tenantId: user.tenantId, actorUserId: user.id, actorSource: "web", requestId, correlationId: request.headers.get("x-correlation-id") ?? requestId, idempotencyKey: request.headers.get("idempotency-key") ?? undefined }; }
function failure(error: unknown, set: { status?: number | string }) { const presented = presentDomainError(error); set.status = presented.status; return presented.body; }
function unauthorized(set: { status?: number | string }) { return failure(new DomainError("UNAUTHORIZED", "Unauthorized", 401), set); }
const invoke = async <T>(user: RouteUser | null, request: Request, set: { status?: number | string }, command: (context: CommandContext) => Promise<T>) => { if (!user) return unauthorized(set); try { return await command(ctx(user, request)); } catch (error) { return failure(error, set); } };
const id = t.String({ format: "uuid" });
const date = t.String({ format: "date" });
const dateTime = t.String({ format: "date-time" });
const money = t.String({ pattern: "^(0|[1-9]\\d*)\\.\\d{2}$", maxLength: 32 });
const allocation = t.Object({ itemPublicId: id, borrowerPublicId: t.Optional(id), loanPublicId: id, schedulePublicId: t.Optional(t.Nullable(id)), amount: money, targetDueDate: date, intent: t.Union([t.Literal("on_time"), t.Literal("advance"), t.Literal("backdated")]) }, { additionalProperties: t.Never() });
const candidateComponents = t.Object({ principal: money, interest: money, fee: money, penalty: money }, { additionalProperties: t.Never() });
const candidateSchedule = t.Object({ publicId: id, dueDate: date, status: t.String(), remainingDue: money, components: candidateComponents }, { additionalProperties: t.Never() });
const candidateContract = t.Object({ borrowerPublicId: id, borrowerName: t.String(), loanPublicId: id, repaymentType: t.String(), status: t.String(), eligible: t.Boolean(), eligibilityCode: t.Nullable(t.String()), principalAmount: money, outstandingPrincipal: money, interestRate: money, startDate: t.Nullable(date), nextDueDate: t.Nullable(date), dueComponents: t.Nullable(candidateComponents), proposalComponents: t.Nullable(candidateComponents), schedules: t.Array(candidateSchedule) }, { additionalProperties: t.Never() });
const candidateOutput = t.Object({ stagingItemPublicId: id, batchItemPublicId: t.Nullable(id), stagingRevision: t.Integer(), batchRevision: t.Integer(), amount: money, receivedAt: dateTime, businessDate: date, inputFingerprint: t.String(), borrowerResolution: t.Union([t.Literal("none"), t.Literal("unique"), t.Literal("ambiguous"), t.Literal("candidates")]), matchType: t.Nullable(t.Union([t.Literal("canonical"), t.Literal("confirmed_alias"), t.Literal("fuzzy")])), borrowerCandidates: t.Array(t.Object({ publicId: id, name: t.String(), matchType: t.Nullable(t.Union([t.Literal("canonical"), t.Literal("confirmed_alias"), t.Literal("fuzzy")] )) }, { additionalProperties: t.Never() })), contractCandidates: t.Array(candidateContract), candidateLimitReached: t.Boolean(), reviewRequired: t.Boolean() }, { additionalProperties: t.Never() });
const candidateResponse = t.Union([candidateOutput, t.Object({ error: t.String(), code: t.String(), details: t.Optional(t.Record(t.String(), t.Unknown())) }, { additionalProperties: t.Never() })]);
export const paymentBatchesRoute = new Elysia({ prefix: "/payment-batches" }).use(authPlugin)
    .post("/", async ({ body, user, request, set }) => { if (!user) return unauthorized(set); try { return await createPaymentBatch(ctx(user, request), body); } catch (error) { return failure(error, set); } }, { body: t.Object({ idempotencyKey: t.String({ minLength: 1, maxLength: 200 }), borrowerPublicId: t.Optional(t.Nullable(id)), notes: t.Optional(t.Nullable(t.String({ maxLength: 2000 }))) }, { additionalProperties: t.Never() }) })
    .get("/:id", async ({ params, user, request, set }) => { if (!user) return unauthorized(set); try { return await getPaymentBatch(ctx(user, request), params.id); } catch (error) { return failure(error, set); } }, { params: t.Object({ id }, { additionalProperties: t.Never() }) })
    .get("/:id/workspace", async ({ params, user, request, set }) => { if (!user) return unauthorized(set); try { return await getPaymentBatchWorkspace(ctx(user, request), params.id); } catch (error) { return failure(error, set); } }, { params: t.Object({ id }, { additionalProperties: t.Never() }) })
    .post("/:id/items", async ({ params, body, user, request, set }) => { if (!user) return unauthorized(set); try { return await addPaymentBatchItem(ctx(user, request), params.id, body); } catch (error) { return failure(error, set); } }, { params: t.Object({ id }, { additionalProperties: t.Never() }), body: t.Object({ paymentIntakePublicId: id, itemOrder: t.Integer({ minimum: 1 }) }, { additionalProperties: t.Never() }) })
    .post("/:id/preview", async ({ params, body, user, request, set }) => { if (!user) return unauthorized(set); try { return await previewPaymentBatch(ctx(user, request), params.id, { ...body, allocations: body.allocations?.map(({ schedulePublicId, ...item }) => ({ ...item, ...(schedulePublicId == null ? {} : { schedulePublicId }) })) }); } catch (error) { return failure(error, set); } }, { params: t.Object({ id }, { additionalProperties: t.Never() }), body: t.Object({ borrowerPublicId: id, decisionPublicId: t.Optional(id), allocations: t.Optional(t.Array(t.Object({ itemPublicId: id, borrowerPublicId: t.Optional(id), loanPublicId: id, schedulePublicId: t.Optional(t.Nullable(id)), amount: money, targetDueDate: date, intent: t.Union([t.Literal("on_time"), t.Literal("advance"), t.Literal("backdated")]) }, { additionalProperties: t.Never() }), { maxItems: 200 })) }, { additionalProperties: t.Never() }) })
    .post("/:id/execute", async ({ params, body, user, request, set }) => { if (!user) return unauthorized(set); try { return await executePaymentBatch(ctx(user, request), params.id, body); } catch (error) { return failure(error, set); } }, { params: t.Object({ id }, { additionalProperties: t.Never() }), body: t.Object({ previewPublicId: id, previewHash: t.String(), confirmationHash: t.String(), confirmed: t.Literal(true), idempotencyKey: t.String({ minLength: 1, maxLength: 200 }) }, { additionalProperties: t.Never() }) });

export const paymentBatchStagingRoute = new Elysia({ prefix: "/payment-batches" }).use(authPlugin)
    .get("/staging/:stagingItemPublicId/candidates", ({ params, query, user, request, set }) => invoke(user, request, set, (commandContext) => discoverPaymentBatchCandidates(commandContext, { stagingItemPublicId: params.stagingItemPublicId, borrowerQuery: query.q, amount: query.amount, receivedAt: query.receivedAt })) as any, { params: t.Object({ stagingItemPublicId: id }, { additionalProperties: t.Never() }), query: t.Object({ q: t.Optional(t.String({ maxLength: 2000 })), amount: t.Optional(money), receivedAt: t.Optional(dateTime) }, { additionalProperties: t.Never() }), response: candidateResponse })
    .post("/stage", async ({ body, user, request, set }) => { if (!user) return unauthorized(set); try { return await stagePaymentBatchItems(ctx(user, request), body); } catch (error) { return failure(error, set); } }, { body: t.Object({ idempotencyKey: t.String({ minLength: 1, maxLength: 200 }), borrowerPublicId: t.Optional(t.Nullable(id)), notes: t.Optional(t.Nullable(t.String({ maxLength: 2000 }))), items: t.Array(t.Object({ clientItemKey: t.String({ minLength: 1, maxLength: 100 }), payerName: t.Optional(t.Nullable(t.String({ maxLength: 500 }))), bankReference: t.Optional(t.Nullable(t.String({ maxLength: 500 }))) }, { additionalProperties: t.Never() }), { minItems: 1, maxItems: 50 }) }, { additionalProperties: t.Never() }) })
    .post("/staging/:stagingItemPublicId/evidence/prepare", async ({ params, body, user, request, set }) => { if (!user) return unauthorized(set); try { return await preparePaymentBatchStagingEvidence(ctx(user, request), { ...body, stagingItemPublicId: params.stagingItemPublicId }); } catch (error) { return failure(error, set); } }, { params: t.Object({ stagingItemPublicId: id }, { additionalProperties: t.Never() }), body: t.Object({ mimeType: t.Union([t.Literal("image/jpeg"), t.Literal("image/png"), t.Literal("application/pdf")]), size: t.Integer({ minimum: 1 }), sha256: t.String({ pattern: "^[0-9a-fA-F]{64}$" }), originalName: t.Optional(t.Nullable(t.String({ maxLength: 500 }))) }, { additionalProperties: t.Never() }) })
    .post("/staging/:stagingItemPublicId/evidence/finalize", async ({ params, body, user, request, set }) => { if (!user) return unauthorized(set); try { return await finalizePaymentBatchStagingEvidence(ctx(user, request), params.stagingItemPublicId, body.evidencePublicId); } catch (error) { return failure(error, set); } }, { params: t.Object({ stagingItemPublicId: id }, { additionalProperties: t.Never() }), body: t.Object({ evidencePublicId: id }, { additionalProperties: t.Never() }) })
    .post("/staging/:stagingItemPublicId/review", async ({ params, body, user, request, set }) => { if (!user) return unauthorized(set); try { return await reviewPaymentBatchStagingItem(ctx(user, request), { ...body, reviewedReason: body.reviewedReason ?? undefined, stagingItemPublicId: params.stagingItemPublicId }); } catch (error) { return failure(error, set); } }, { params: t.Object({ stagingItemPublicId: id }, { additionalProperties: t.Never() }), body: t.Object({ amount: money, receivedAt: dateTime, intakeIdempotencyKey: t.String({ minLength: 1, maxLength: 200 }), reviewedReason: t.Optional(t.Nullable(t.String({ maxLength: 2000 }))), reviewedRangeFrom: t.Optional(date), reviewedRangeTo: t.Optional(date) }, { additionalProperties: t.Never() }) });
export const paymentBatchStagingEditRoute = new Elysia({ prefix: "/payment-batches" }).use(authPlugin)
    .post("/staging/:stagingItemPublicId/edit", async ({ params, body, user, request, set }) => { if (!user) return unauthorized(set); try { return await editPaymentBatchStagingItem(ctx(user, request), { ...body, stagingItemPublicId: params.stagingItemPublicId }); } catch (error) { return failure(error, set); } }, { params: t.Object({ stagingItemPublicId: id }, { additionalProperties: t.Never() }), body: t.Object({ expectedRevision: t.Integer({ minimum: 1 }), idempotencyKey: t.String({ minLength: 1, maxLength: 200 }), reason: t.String({ minLength: 1, maxLength: 2000 }), amount: t.Optional(money), receivedAt: t.Optional(dateTime), mapping: t.Optional(t.Nullable(t.Object({ borrowerPublicId: t.Optional(id), loanPublicId: t.Optional(id), schedulePublicId: t.Optional(id) }, { additionalProperties: t.Never() }))) }, { additionalProperties: t.Never() }) })
    .post("/:id/split", async ({ params, body, user, request, set }) => { if (!user) return unauthorized(set); try { return await splitPaymentBatch(ctx(user, request), params.id, body); } catch (error) { return failure(error, set); } }, { params: t.Object({ id }, { additionalProperties: t.Never() }), body: t.Object({ selectedItemPublicIds: t.Array(id, { minItems: 1, maxItems: 50 }), expectedSourceRevision: t.Integer({ minimum: 1 }), idempotencyKey: t.String({ minLength: 1, maxLength: 200 }), reason: t.String({ minLength: 1, maxLength: 2000 }) }, { additionalProperties: t.Never() }) });

export const paymentBatchDecisionRoute = new Elysia({ prefix: "/payment-batches" }).use(authPlugin)
    .post("/:id/decision", async ({ params, body, user, request, set }) => { if (!user) return unauthorized(set); try { return await decidePaymentBatch(ctx(user, request), params.id, body); } catch (error) { return failure(error, set); } }, { params: t.Object({ id }, { additionalProperties: t.Never() }), body: t.Object({ previewPublicId: id, previewHash: t.String(), revision: t.Integer({ minimum: 0 }), action: t.Literal("confirm_no_older_pending"), reason: t.String({ minLength: 1, maxLength: 2000 }), fromDate: date, toDate: date, idempotencyKey: t.String({ minLength: 1, maxLength: 200 }) }, { additionalProperties: t.Never() }) });

export const paymentBatchCancelRoute = new Elysia({ prefix: "/payment-batches" }).use(authPlugin)
    .post("/:id/cancel", async ({ params, body, user, request, set }) => { if (!user) return unauthorized(set); try { return await cancelPaymentBatch(ctx(user, request), params.id, body); } catch (error) { return failure(error, set); } }, { params: t.Object({ id }, { additionalProperties: t.Never() }), body: t.Object({ reason: t.String({ minLength: 1, maxLength: 2000 }), revision: t.Integer({ minimum: 0 }), idempotencyKey: t.String({ minLength: 1, maxLength: 200 }) }, { additionalProperties: t.Never() }) });
